#!/usr/bin/env node
/**
 * Generates assets/sparkle.svg: the glitter for the holographic card.
 *
 * Why a generated file and not CSS gradients: tiled CSS gradients repeat every
 * few em, so the dots line up into a visible grid. This is one large tile with
 * an irregular, evenly spread set of dots (Poisson-disc sampling with a fixed
 * seed), so it never looks like a lattice. It wraps around at the edges
 * (distances are measured on a torus and edge dots are drawn on both sides), so
 * the tile repeats without a seam. One SVG unit = 1em of the card.
 *
 * Usage: node tools/generate-sparkle.js     (deterministic: same output every run)
 */
'use strict';

const fs = require('fs');
const path = require('path');

const OUT = path.resolve(__dirname, '..', 'assets', 'sparkle.svg');

// Tile size in em. Much larger than the card (90 x 55) plus the drift of the
// glitter layer (about 18 x 11), so a repeat is never visible at the same time.
const W = 200;
const H = 120;
const MIN_DISTANCE = 10;    // em between any two dots
const TARGET_DOTS = 170;
const SEED = 20260929;
const MIN_CORE = 0.07;      // radius of the finest specks, em
const MAX_CORE = 0.19;      // radius of the largest dots, em (halo reaches 2.7x this)

// Small deterministic PRNG (mulberry32)
function rng(seed) {
    let a = seed >>> 0;
    return () => {
        a = (a + 0x6D2B79F5) >>> 0;
        let t = a;
        t = Math.imul(t ^ (t >>> 15), t | 1);
        t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
}
const random = rng(SEED);

/** Shortest distance on the wrapped tile. */
function wrappedDistance(a, b) {
    const dx = Math.min(Math.abs(a.x - b.x), W - Math.abs(a.x - b.x));
    const dy = Math.min(Math.abs(a.y - b.y), H - Math.abs(a.y - b.y));
    return Math.hypot(dx, dy);
}

// Dart throwing: keep a random point only if it is far enough from all others.
const dots = [];
for (let attempt = 0; attempt < 20000 && dots.length < TARGET_DOTS; attempt++) {
    const p = { x: random() * W, y: random() * H };
    if (dots.every((q) => wrappedDistance(p, q) >= MIN_DISTANCE)) dots.push(p);
}

// Sizes: mostly fine specks, a few larger dots (cubing skews toward small).
for (const d of dots) {
    d.core = MIN_CORE + (MAX_CORE - MIN_CORE) * Math.pow(random(), 3); // bright core radius, em
    d.tint = random() < 0.5 ? 'w' : 's';          // white or cool silver
}

const HALO = 2.7; // the soft halo reaches this many core radii out
const fmt = (n) => Number(n.toFixed(2));
const circles = [];
for (const d of dots) {
    const r = d.core * HALO;
    // Draw a copy on the opposite side when the halo crosses an edge (seamless wrap)
    const xs = [d.x];
    const ys = [d.y];
    if (d.x < r) xs.push(d.x + W);
    if (d.x > W - r) xs.push(d.x - W);
    if (d.y < r) ys.push(d.y + H);
    if (d.y > H - r) ys.push(d.y - H);
    for (const x of xs) {
        for (const y of ys) {
            circles.push(`<circle cx="${fmt(x)}" cy="${fmt(y)}" r="${fmt(r)}" fill="url(#${d.tint})"/>`);
        }
    }
}

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}">
<!-- Generated by tools/generate-sparkle.js. Do not edit by hand. -->
<defs>
<radialGradient id="w"><stop offset="0" stop-color="#fff"/><stop offset="0.37" stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient>
<radialGradient id="s"><stop offset="0" stop-color="#e4eaf1"/><stop offset="0.37" stop-color="#e4eaf1"/><stop offset="1" stop-color="#e4eaf1" stop-opacity="0"/></radialGradient>
</defs>
${circles.join('\n')}
</svg>
`;

fs.writeFileSync(OUT, svg);
console.log(`${dots.length} dots (${circles.length} circles incl. wrap copies) written to ${path.relative(process.cwd(), OUT)} (${svg.length} bytes).`);
