#!/usr/bin/env node
/**
 * Generates the QR code for the stamp and writes it into index.html, between
 * the `<!-- qr:start -->` and `<!-- qr:end -->` markers, as one inline SVG path.
 *
 * The QR is static, so it is rendered at build time instead of shipping a QR
 * library to every visitor. The generator is the vendored qrcodejs
 * (tools/vendor/qrcode.min.js, MIT), run against a stub DOM.
 *
 * Usage:  node tools/generate-qr.js [url]        (default: https://haodong.page)
 *         node tools/generate-qr.js --print [url] (print the SVG, don't touch index.html)
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.resolve(__dirname, '..');
const HTML_PATH = path.join(ROOT, 'index.html');
const LIB_PATH = path.join(__dirname, 'vendor', 'qrcode.min.js');
const INK = '#2C2825'; // dark modules; the tile behind them is always white

/** Loads qrcodejs in a sandbox with just enough fake DOM for its constructor. */
function loadQRCode() {
    const fakeElement = () => ({
        style: {},
        appendChild() {},
        innerHTML: '',
        // qrcodejs' table renderer measures the table it just built
        childNodes: [{ offsetWidth: 0, offsetHeight: 0, style: {} }],
        getContext: () => ({})
    });
    const sandbox = {
        document: { createElement: fakeElement, documentElement: { tagName: 'html' } },
        navigator: { userAgent: '' }
    };
    sandbox.window = sandbox;
    vm.createContext(sandbox);
    vm.runInContext(fs.readFileSync(LIB_PATH, 'utf8'), sandbox);
    return sandbox.QRCode;
}

/** Returns the module matrix (true = dark) for `text` at error-correction level M. */
function qrMatrix(text) {
    const QRCode = loadQRCode();
    const qr = new QRCode(fakeHost(), {
        text, width: 64, height: 64, correctLevel: QRCode.CorrectLevel.M
    });
    const model = qr._oQRCode;
    const n = model.getModuleCount();
    const rows = [];
    for (let r = 0; r < n; r++) {
        const row = [];
        for (let c = 0; c < n; c++) row.push(Boolean(model.isDark(r, c)));
        rows.push(row);
    }
    return rows;
}

function fakeHost() {
    return { style: {}, appendChild() {}, innerHTML: '', childNodes: [{ offsetWidth: 0, offsetHeight: 0, style: {} }], getContext: () => ({}) };
}

/** One SVG path: horizontal runs of dark modules, `M x y h<run> v1 h-<run> z`. */
function svgFor(matrix) {
    const n = matrix.length;
    let d = '';
    for (let y = 0; y < n; y++) {
        let x = 0;
        while (x < n) {
            if (!matrix[y][x]) { x++; continue; }
            let run = 0;
            while (x + run < n && matrix[y][x + run]) run++;
            d += `M${x} ${y}h${run}v1h-${run}z`;
            x += run;
        }
    }
    return `<svg viewBox="0 0 ${n} ${n}" aria-hidden="true" focusable="false">` +
        `<path fill="${INK}" d="${d}"/></svg>`;
}

function main() {
    const args = process.argv.slice(2);
    const printOnly = args.includes('--print');
    const url = args.find((a) => !a.startsWith('--')) || 'https://haodong.page';

    const svg = svgFor(qrMatrix(url));
    if (printOnly) {
        console.log(svg);
        return;
    }

    const html = fs.readFileSync(HTML_PATH, 'utf8');
    const block = /([ \t]*)<!-- qr:start[^>]*-->[\s\S]*?<!-- qr:end -->/;
    const match = html.match(block);
    if (!match) {
        console.error('index.html has no <!-- qr:start --> ... <!-- qr:end --> block.');
        process.exit(1);
    }
    const indent = match[1];
    const replacement =
        `${indent}<!-- qr:start (generated by tools/generate-qr.js for ${url}, do not edit by hand) -->\n` +
        `${indent}${svg}\n` +
        `${indent}<!-- qr:end -->`;
    fs.writeFileSync(HTML_PATH, html.replace(block, replacement));
    console.log(`QR for ${url} written to index.html (${svg.length} bytes).`);
}

main();
